const JWT_REFRESH_LENGTH = process.env.BACKEND_JWT_REFRESH_LENGTH
const JWT_USER_HEADER = process.env.BACKEND_JWT_USER_HEADER
const JWT_HEADER_NAME = process.env.BACKEND_JWT_HEADER_NAME
const JWT_AUTHENTICATION_WORD = process.env.BACKEND_JWT_AUTHENTICATION_WORD

export { 
    JWT_USER_HEADER,
    JWT_HEADER_NAME,
    JWT_REFRESH_LENGTH,
    JWT_AUTHENTICATION_WORD
}