# The docker-compose version
version: '3'

# Define services of project
services:

  # Frontend container
  frontend:
    container_name: sitefodi-frontend
    build: ./frontend
    image: rsfront
    ports:
      - 3000:3000
    env_file:
      - ../.env/frontend_connections
    links:
      - backend
    depends_on:
      - backend
      - database
    volumes:
      # - ./frontend:/usr/src/app
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: ["npm", "start"]
    networks:
      - sitefodi

  # Backend container
  backend:
    container_name: sitefodi-backend
    build: ./backend
    image: mmapi
    ports:
      - 4000:4000
      - 5000:5000
    env_file:
      - ../.env/backend_conf
      - ../.env/backend_keys
      - ../.env/backend_databases
      - ../.env/backend_jwt
      - ../.env/mysql
    depends_on:
      - database
    volumes:
      - ./backend/:/usr/src/app
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: ["npm", "run", "dev"]
    networks:
      - sitefodi

  # Database container
  database:
    container_name: sitefodi-db
    image: 'mysql:5.7'
    ports:
      - 3306:3306
    env_file:
      - ../.env/mysql
      - ../.env/root_mysql
    volumes:
      - ./database/dump:/docker-entrypoint-initdb.d
      - ./database/mysql.conf.d:/etc/mysql/mysql.conf.d
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - sitefodi

networks:
  sitefodi:
    name: sitefodi_net